// Edge Function: create-package
// Creates a new package, sends email notification to receiver, and logs audit entry
// Deno runtime for Supabase Edge Functions

import { serve } from 'https://deno.land/std@0.177.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.45.0'

interface PackageItemRequest {
  quantity: number
  description: string
  /**
   * Optional inventory_items.id this package item is sourced from. When
   * present, the link is persisted on package_items so later edits can
   * reconcile inventory stock.
   */
  inventory_item_id?: string | null
}

interface CreatePackageRequest {
  receiver_email: string
  notes?: string
  items?: PackageItemRequest[]
  delivery_location_id?: string
  po_number?: string
}

interface PackageItemResponse {
  id: string
  quantity: number
  description: string
  inventory_item_id: string | null
}

interface PackageResponse {
  id: string
  reference: string
  receiver_email: string
  notes: string | null
  status: string
  created_at: string
  items: PackageItemResponse[]
}

function buildCorsHeaders(origin: string | null) {
  return {
    'Access-Control-Allow-Origin': origin ?? '*',
    'Access-Control-Allow-Methods': 'POST, OPTIONS',
    'Access-Control-Allow-Headers': 'Authorization, X-Requested-With, X-Client-Info, apikey, Content-Type',
    'Access-Control-Allow-Credentials': 'true',
    'Access-Control-Max-Age': '86400'
  }
}

serve(async (req) => {
  const origin = req.headers.get('origin')
  const corsHeaders = buildCorsHeaders(origin)

  // Handle CORS preflight
  if (req.method === 'OPTIONS') {
    return new Response(null, { status: 204, headers: corsHeaders })
  }

  try {
    const authHeader = req.headers.get('Authorization')
    if (!authHeader) {
      return new Response(
        JSON.stringify({ error: 'Missing authorization header' }),
        { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    const supabaseUrl = Deno.env.get('SUPABASE_URL')!
    const supabaseAnonKey = Deno.env.get('SUPABASE_ANON_KEY')!
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!

    // User client to verify caller
    const userClient = createClient(supabaseUrl, supabaseAnonKey, {
      global: { headers: { Authorization: authHeader } }
    })

    const { data: { user: callingUser }, error: userError } = await userClient.auth.getUser()
    if (userError || !callingUser) {
      return new Response(
        JSON.stringify({
          error: 'Unauthorized',
          details: userError?.message || 'Could not verify user token'
        }),
        { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    // Check if calling user is warehouse or admin
    const { data: callerProfile, error: profileError } = await userClient
      .from('staff_profiles')
      .select('role, full_name')
      .eq('user_id', callingUser.id)
      .single()

    if (profileError || !callerProfile) {
      return new Response(
        JSON.stringify({
          error: 'Staff profile not found',
          details: profileError?.message
        }),
        { status: 403, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    if (!['warehouse', 'admin'].includes(callerProfile.role)) {
      return new Response(
        JSON.stringify({
          error: 'Only warehouse staff and admins can create packages',
          details: `User role is '${callerProfile.role}'`
        }),
        { status: 403, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    // Parse request body
    const body: CreatePackageRequest = await req.json()
    const { receiver_email, notes, items, delivery_location_id, po_number } = body

    if (!receiver_email) {
      return new Response(
        JSON.stringify({ error: 'Missing required field: receiver_email' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    // Validate email format
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
    if (!emailRegex.test(receiver_email)) {
      return new Response(
        JSON.stringify({ error: 'Invalid email format' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    // Admin client for operations
    const adminClient = createClient(supabaseUrl, supabaseServiceKey, {
      auth: { autoRefreshToken: false, persistSession: false }
    })

    // Create package (reference is auto-generated by trigger)
    const { data: newPackage, error: packageError } = await adminClient
      .from('packages')
      .insert({
        receiver_email: receiver_email.toLowerCase().trim(),
        notes: notes?.trim() || null,
        created_by: callingUser.id,
        status: 'pending',
        delivery_location_id: delivery_location_id || null,
        po_number: po_number?.trim() || null
      })
      .select()
      .single()

    if (packageError) {
      console.error('Package creation error:', packageError)
      return new Response(
        JSON.stringify({
          error: 'Failed to create package',
          details: packageError.message
        }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    // Insert package items if provided
    let packageItems: PackageItemResponse[] = []
    if (items && items.length > 0) {
      const itemsToInsert = items
        .filter(item => item.description?.trim() && item.quantity > 0)
        .map(item => ({
          package_id: newPackage.id,
          quantity: item.quantity,
          description: item.description.trim(),
          inventory_item_id: item.inventory_item_id ?? null
        }))

      if (itemsToInsert.length > 0) {
        const { data: insertedItems, error: itemsError } = await adminClient
          .from('package_items')
          .insert(itemsToInsert)
          .select('id, quantity, description, inventory_item_id')

        if (itemsError) {
          console.error('Items insertion error:', itemsError)
          // Don't fail the entire request, package was created successfully
        } else if (insertedItems) {
          packageItems = insertedItems
        }
      }
    }

    // Fetch delivery location details if provided
    let deliveryLocation: { name: string; address: string; google_maps_link: string | null } | null = null
    if (delivery_location_id) {
      const { data: locationData, error: locationError } = await adminClient
        .from('delivery_locations')
        .select('name, address, google_maps_link')
        .eq('id', delivery_location_id)
        .single()

      if (!locationError && locationData) {
        deliveryLocation = locationData
      }
    }

    // Send email notification to receiver
    let emailSent = false
    let emailError: string | null = null

    try {
      // Use Resend API if configured, otherwise log for manual follow-up
      const resendApiKey = Deno.env.get('RESEND_API_KEY')
      const collectionHoursWeekday = Deno.env.get('COLLECTION_HOURS') || 'Monday to Friday, 7:00 AM - 16:00 PM'
      const collectionHoursSaturday = Deno.env.get('COLLECTION_HOURS_SATURDAY') || 'Saturdays: Closed'
      const collectionHoursSunday = Deno.env.get('COLLECTION_HOURS_SUNDAY') || 'Sundays: Closed'
      const collectionHoursHolidays = Deno.env.get('COLLECTION_HOURS_HOLIDAYS') || 'Holidays: Closed'
      const supportEmail = Deno.env.get('SUPPORT_EMAIL') || 'rabelanimm@gmail.com'
      const collectionContact = Deno.env.get('COLLECTION_CONTACT') || 'Ext 4536 and ask for Lesedi or Thato'
      const reviewFormUrl = Deno.env.get('REVIEW_FORM_URL') || 'https://docs.google.com/forms/d/e/1FAIpQLSdiySN-ONYROMnjfqAo4fkHyihRWdhD0sUmIu4L8k6UXcGsNg/viewform?usp=preview'
      const reviewQrCodeUrl = `https://api.qrserver.com/v1/create-qr-code/?size=180x180&margin=10&data=${encodeURIComponent(reviewFormUrl)}`

      // Use delivery location if available, otherwise fall back to environment variable
      const locationName = deliveryLocation?.name || Deno.env.get('COLLECTION_LOCATION') || 'the designated collection point'
      const locationAddress = deliveryLocation?.address || ''
      const locationMapsLink = deliveryLocation?.google_maps_link || null

      if (resendApiKey) {
        const emailResponse = await fetch('https://api.resend.com/emails', {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${resendApiKey}`,
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            from: Deno.env.get('EMAIL_FROM') || 'POD System <noreply@example.com>',
            to: [receiver_email],
            subject: `Purchase Order Confirmation${po_number ? ` - ${po_number}` : ''} - ${newPackage.reference}`,
            html: `
              <!DOCTYPE html>
              <html>
              <head>
                <meta charset="utf-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
              </head>
              <body style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; color: #242424; background: #ffffff;">
                <!-- Brand bar -->
                <div style="background: #ffffff; padding: 24px 24px 16px 24px; border: 1px solid #ededed; border-bottom: 4px solid #f75757; border-radius: 8px 8px 0 0; text-align: center;">
                  <a href="https://www.rabelanimm.co.za/" style="text-decoration: none; display: inline-block;">
                    <img src="https://www.rabelanimm.co.za/images/logo.png" alt="Rabelani MM Trading Enterprise" style="max-height: 70px; height: auto; width: auto; display: block; margin: 0 auto;" />
                  </a>
                  <p style="margin: 12px 0 0 0; font-size: 12px; color: #919194; letter-spacing: 0.08em; text-transform: uppercase;">Rabelani MM Trading Enterprise</p>
                </div>

                <!-- Title block -->
                <div style="background: #f75757; padding: 28px 24px; text-align: center;">
                  <h1 style="color: #ffffff; margin: 0; font-size: 24px; font-weight: 700; letter-spacing: 0.01em;">Purchase Order Confirmation</h1>
                  ${po_number ? `<p style="color: #ffe7e7; margin: 14px 0 0 0; font-size: 15px;">Purchase Order Number: <strong style="font-family: 'Courier New', monospace; color: #ffffff;">${po_number}</strong></p>` : ''}
                  <p style="color: #ffe7e7; margin: 6px 0 0 0; font-size: 15px;">Your Package Reference: <strong style="font-family: 'Courier New', monospace; color: #ffffff;">${newPackage.reference}</strong></p>
                </div>

                <div style="background: #ffffff; padding: 30px 28px; border: 1px solid #ededed; border-top: none;">
                  <h2 style="color: #242424; font-size: 20px; margin: 0 0 15px 0; font-weight: 700;">📦 Package Being Prepared</h2>
                  <p style="margin: 0 0 12px 0; color: #4e595f;">Hello,</p>
                  <p style="margin: 0 0 20px 0; color: #4e595f; line-height: 1.6;">Great news! A package has been registered for you and is currently being prepared for delivery.</p>

                  ${notes ? `
                  <div style="background: #fff8f8; padding: 15px; border-radius: 6px; margin: 20px 0; border-left: 4px solid #b99769;">
                    <p style="margin: 0; font-size: 14px; color: #242424;"><strong>📝 Notes:</strong> ${notes}</p>
                  </div>
                  ` : ''}

                  ${packageItems.length > 0 ? `
                  <div style="margin: 24px 0;">
                    <h3 style="color: #242424; font-size: 16px; margin: 0 0 12px 0; font-weight: 700;">📋 Package Contents</h3>
                    <table style="width: 100%; border-collapse: collapse; border: 1px solid #ededed; border-radius: 6px; overflow: hidden;">
                      <thead>
                        <tr style="background: #fafafa;">
                          <th style="padding: 12px; text-align: left; border-bottom: 1px solid #ededed; font-size: 12px; color: #919194; text-transform: uppercase; letter-spacing: 0.05em; width: 60px;">Qty</th>
                          <th style="padding: 12px; text-align: left; border-bottom: 1px solid #ededed; font-size: 12px; color: #919194; text-transform: uppercase; letter-spacing: 0.05em;">Description</th>
                        </tr>
                      </thead>
                      <tbody>
                        ${packageItems.map(item => `
                        <tr>
                          <td style="padding: 12px; border-bottom: 1px solid #ededed; font-size: 14px; color: #242424; font-weight: 600;">${item.quantity}</td>
                          <td style="padding: 12px; border-bottom: 1px solid #ededed; font-size: 14px; color: #4e595f;">${item.description}</td>
                        </tr>
                        `).join('')}
                      </tbody>
                    </table>
                  </div>
                  ` : ''}

                  <h3 style="color: #242424; font-size: 16px; margin: 30px 0 10px 0; font-weight: 700;">📍 Delivery Point</h3>
                  <div style="background: #fafafa; padding: 20px; border-radius: 6px; margin: 10px 0 20px 0; border-left: 4px solid #f75757;">
                    <p style="font-size: 16px; font-weight: 700; color: #242424; margin: 0;">${locationName}</p>
                    ${locationAddress ? `<p style="font-size: 14px; color: #4e595f; margin: 8px 0 0 0; line-height: 1.5;">${locationAddress}</p>` : ''}
                    <p style="font-size: 14px; color: #4e595f; margin: 10px 0 0 0;"><strong style="color: #242424;">Contact Number:</strong> ${collectionContact}</p>
                    ${locationMapsLink ? `<p style="margin: 12px 0 0 0;"><a href="${locationMapsLink}" style="color: #f75757; font-size: 14px; text-decoration: none; font-weight: 600;">📍 View on Google Maps</a></p>` : ''}
                  </div>

                  <div style="margin: 24px 0;">
                    <p style="margin: 0 0 8px 0; font-size: 14px; color: #242424;"><strong>Collection Hours:</strong></p>
                    <ul style="margin: 0; padding-left: 20px; font-size: 14px; color: #4e595f; line-height: 1.7;">
                      <li>${collectionHoursWeekday}</li>
                      <li>${collectionHoursSaturday}</li>
                      <li>${collectionHoursSunday}</li>
                      <li>${collectionHoursHolidays}</li>
                    </ul>
                  </div>

                  <div style="background: #fff8f8; padding: 20px; border-radius: 6px; margin: 24px 0; border-left: 4px solid #c54041;">
                    <h3 style="color: #c54041; font-size: 16px; margin: 0 0 10px 0; font-weight: 700;">⏳ What happens next?</h3>
                    <ul style="margin: 0; padding-left: 20px; font-size: 14px; color: #4e595f; line-height: 1.7;">
                      <li style="margin-bottom: 6px;">Your package is being prepared at our warehouse</li>
                      <li style="margin-bottom: 6px;">You'll receive an email when your package is on its way</li>
                      <li>Once it arrives at the collection point, you'll get a final notification that it's ready for pickup</li>
                    </ul>
                  </div>

                  <div style="background: #fafafa; padding: 18px; border-radius: 6px; margin: 24px 0;">
                    <p style="margin: 0 0 8px 0; font-size: 14px; color: #242424;"><strong>What to bring when collecting:</strong></p>
                    <ul style="margin: 0; padding-left: 20px; font-size: 14px; color: #4e595f; line-height: 1.7;">
                      <li>Your PO reference number (shown above)</li>
                      <li>Valid Staff Employee Card for verification and a Witness to Sign with</li>
                    </ul>
                  </div>
                </div>

                <!-- Footer -->
                <div style="background: #242424; padding: 28px 24px; border-radius: 0 0 8px 8px; text-align: center;">
                  <p style="margin: 0 0 12px 0; font-size: 14px; color: #c9c9c9;">
                    Questions? Contact us at <a href="mailto:${supportEmail}" style="color: #f75757; text-decoration: none; font-weight: 600;">${supportEmail}</a>
                  </p>
                  <p style="margin: 0 0 18px 0; font-size: 11px; color: #919194; line-height: 1.5;">
                    This is an automated message from the POD System. Please do not reply directly to this email.
                  </p>
                  <div style="background: #ffffff; display: inline-block; padding: 14px; border-radius: 8px; margin: 0 0 14px 0;">
                    <img src="${reviewQrCodeUrl}" alt="Scan to review our services" width="160" height="160" style="display: block; width: 160px; height: 160px;" />
                  </div>
                  <p style="margin: 0 0 14px 0; font-size: 12px; color: #c9c9c9; letter-spacing: 0.04em;">
                    Scan the QR code to review our services
                  </p>
                  <a href="${reviewFormUrl}" style="display: inline-block; padding: 12px 28px; background: #f75757; color: #ffffff; text-decoration: none; font-size: 13px; font-weight: 700; letter-spacing: 0.08em; text-transform: uppercase; border-radius: 50px;">
                    Please Review Our Services
                  </a>
                  <p style="margin: 18px 0 0 0; font-size: 11px; color: #666666;">
                    &copy; ${new Date().getFullYear()} Rabelani MM Trading Enterprise &middot; <a href="https://www.rabelanimm.co.za/" style="color: #919194; text-decoration: none;">www.rabelanimm.co.za</a>
                  </p>
                </div>
              </body>
              </html>
            `
          })
        })

        if (emailResponse.ok) {
          emailSent = true
          // Update package status to notified
          await adminClient
            .from('packages')
            .update({ status: 'notified' })
            .eq('id', newPackage.id)

          newPackage.status = 'notified'

          // Log PACKAGE_PREPARED_NOTIFICATION audit event
          await adminClient
            .from('audit_logs')
            .insert({
              action: 'PACKAGE_PREPARED_NOTIFICATION',
              entity_type: 'package',
              entity_id: newPackage.id,
              performed_by: callingUser.id,
              metadata: {
                reference: newPackage.reference,
                receiver_email: newPackage.receiver_email,
                notification_type: 'email',
                notification_status: 'sent',
                email_subject: 'Package Being Prepared'
              }
            })
        } else {
          const errorBody = await emailResponse.text()
          emailError = `Email API error: ${errorBody}`
          console.error('Email send failed:', emailError)
        }
      } else {
        emailError = 'Email service not configured (RESEND_API_KEY not set)'
        console.log('Email notification skipped:', emailError)
      }
    } catch (e: unknown) {
      const errorMessage = e instanceof Error ? e.message : String(e)
      emailError = `Email exception: ${errorMessage}`
      console.error('Email send exception:', e)
    }

    // Create audit log entry
    const { error: auditError } = await adminClient
      .from('audit_logs')
      .insert({
        action: 'PACKAGE_CREATED',
        entity_type: 'package',
        entity_id: newPackage.id,
        performed_by: callingUser.id,
        metadata: {
          reference: newPackage.reference,
          receiver_email: newPackage.receiver_email,
          notes: newPackage.notes,
          items_count: packageItems.length,
          email_sent: emailSent,
          email_error: emailError,
          created_by_name: callerProfile.full_name
        }
      })

    if (auditError) {
      console.error('Audit log error:', auditError)
      // Don't fail the request for audit log errors
    }

    // Return created package
    const response: PackageResponse = {
      id: newPackage.id,
      reference: newPackage.reference,
      receiver_email: newPackage.receiver_email,
      notes: newPackage.notes,
      status: newPackage.status,
      created_at: newPackage.created_at,
      items: packageItems
    }

    return new Response(
      JSON.stringify({
        package: response,
        email_sent: emailSent,
        email_error: emailError
      }),
      { status: 201, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )

  } catch (error: unknown) {
    console.error('Unexpected error:', error)
    const errorMessage = error instanceof Error ? error.message : String(error)
    return new Response(
      JSON.stringify({
        error: 'Internal server error',
        details: errorMessage
      }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )
  }
})
