// AUTO-GENERATED FILE - do not edit by hand.
// Regenerated by scripts/generate-version.mjs from the git history.
export interface AppVersion {
  /** Display version, e.g. "1.4.2" or "1.4.2-dev" when the tree is dirty. */
  version: string;
  /** Pure MAJOR.MINOR.PATCH derived from Conventional Commits. */
  semver: string;
  /** The tag that semver was computed from, or null when no base tag exists. */
  baseTag: string | null;
  /** Number of bump-worthy commits since baseTag (or since the first commit). */
  commitsSinceBase: number;
  /** True when the working tree had uncommitted changes at build time. */
  isDirty: boolean;
  /** Short commit hash (e.g. "bcff3bb"). */
  hash: string;
  /** Full commit hash. */
  fullHash: string;
  /** Current branch name. */
  branch: string;
  /** First line of the latest commit message. */
  message: string;
  /** ISO-8601 commit timestamp. */
  commitDate: string;
  /** ISO-8601 build timestamp. */
  buildDate: string;
}

export const APP_VERSION: AppVersion = {
  "version": "0.40.0-dev",
  "semver": "0.40.0",
  "baseTag": null,
  "commitsSinceBase": 42,
  "isDirty": true,
  "hash": "d0fa453",
  "fullHash": "d0fa45301392162d48a64dee8f26d2f9019122de",
  "branch": "main",
  "message": "feat!: Version 1",
  "commitDate": "2026-05-08T20:32:11+02:00",
  "buildDate": "2026-05-10T14:08:38.215Z"
};
