// AUTO-GENERATED FILE - do not edit by hand.
// Regenerated by scripts/generate-version.mjs from the git history.
export interface AppVersion {
  /** Display version, e.g. "1.4.2" or "1.4.2-dev" when the tree is dirty. */
  version: string;
  /** Pure MAJOR.MINOR.PATCH derived from Conventional Commits. */
  semver: string;
  /** The tag that semver was computed from, or null when no base tag exists. */
  baseTag: string | null;
  /** Number of bump-worthy commits since baseTag (or since the first commit). */
  commitsSinceBase: number;
  /** True when the working tree had uncommitted changes at build time. */
  isDirty: boolean;
  /** Short commit hash (e.g. "bcff3bb"). */
  hash: string;
  /** Full commit hash. */
  fullHash: string;
  /** Current branch name. */
  branch: string;
  /** First line of the latest commit message. */
  message: string;
  /** ISO-8601 commit timestamp. */
  commitDate: string;
  /** ISO-8601 build timestamp. */
  buildDate: string;
}

export const APP_VERSION: AppVersion = {
  "version": "0.38.0-dev",
  "semver": "0.38.0",
  "baseTag": null,
  "commitsSinceBase": 40,
  "isDirty": true,
  "hash": "bcff3bb",
  "fullHash": "bcff3bbf019d77868c1676553b1fd9e6c57a8ae4",
  "branch": "main",
  "message": "feat: enhance package search functionality to include receiver name lookup",
  "commitDate": "2026-05-07T14:24:02+02:00",
  "buildDate": "2026-05-07T12:46:03.422Z"
};
