// AUTO-GENERATED FILE - do not edit by hand.
// Regenerated by scripts/generate-version.mjs from the git history.
export interface AppVersion {
  /** Full SemVer 2.0.0 string, e.g. "1.4.2", "1.4.2-dev.7" or "1.4.2-dev.7+9f1c2ab.dirty". */
  version: string;
  /** Core MAJOR.MINOR.PATCH derived from Conventional Commits. */
  semver: string;
  /** Numeric MAJOR component. */
  major: number;
  /** Numeric MINOR component. */
  minor: number;
  /** Numeric PATCH component. */
  patch: number;
  /** Prerelease label (e.g. "dev.7"), or null on a stable release branch. */
  prerelease: string | null;
  /** Build metadata (e.g. "9f1c2ab.dirty"), or null when unavailable. */
  buildMetadata: string | null;
  /** Release channel: "stable", "dev", or a sanitized branch name. */
  channel: string;
  /** The tag that semver was computed from, or null when no base tag exists. */
  baseTag: string | null;
  /** Number of commits since baseTag (or since the first commit). */
  commitsSinceBase: number;
  /** Number of bump-worthy (feat/fix/perf/breaking) commits since baseTag. */
  bumpsSinceBase: number;
  /** True when the working tree had uncommitted changes at build time. */
  isDirty: boolean;
  /** True for a clean build on a release branch (main/master/release/hotfix). */
  isRelease: boolean;
  /** Short commit hash (e.g. "bcff3bb"). */
  hash: string;
  /** Full commit hash. */
  fullHash: string;
  /** Current branch name. */
  branch: string;
  /** First line of the latest commit message. */
  message: string;
  /** ISO-8601 commit timestamp. */
  commitDate: string;
  /** ISO-8601 build timestamp. */
  buildDate: string;
}

export const APP_VERSION: AppVersion = {
  "version": "1.6.0-dev.23+7fbc218.dirty",
  "semver": "1.6.0",
  "major": 1,
  "minor": 6,
  "patch": 0,
  "prerelease": "dev.23",
  "buildMetadata": "7fbc218.dirty",
  "channel": "dev",
  "baseTag": "v1.0.0",
  "commitsSinceBase": 23,
  "bumpsSinceBase": 8,
  "isDirty": true,
  "isRelease": false,
  "hash": "7fbc218",
  "fullHash": "7fbc218c8dd937bf2ace686a82c99f17d05c790d",
  "branch": "dev",
  "message": "Merge branch 'dev'",
  "commitDate": "2026-07-01T09:21:45+02:00",
  "buildDate": "2026-07-01T11:08:40.731Z"
};
